before:
  hooks:
    - go mod download
    - cd config/ && npm i && npm run build && cd ..
    - cd assets && go run . && cd ..
    - packr2

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

release:
  github:
  disable: true
