name: Create unsigned macOS build artifact

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvm

    - name: Use Node.js (.nvmrc)
      uses: actions/setup-node@v1
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"

    - name: Build application
      run: cp -R . ~/go/src/github.com/MagicCap/MagicCap && cd ~/go/src/github.com/MagicCap/MagicCap && ./mac_build.sh
      with:
        name: magiccap-darwin
        path: ~/go/src/github.com/MagicCap/MagicCap/magiccap-darwin
